### ISSUE TITLE
contributing mongodb aggregation and view's

### ISSUE THREAD

**Issue by burdettadam** [Patrik-Stas/indyscan#11]
I would like to contribute some aggregations and views into indyscan. How can I contribute?

**Comment by Patrik-Stas** [comment]
Hi @burdettadam thank you for the interest! 

I am planning to migrate from Mongo to Elasticsearch so contributions there instead would be highly appreciated. In fact there's some code already set up for this, you can find some (far from implemented) elasticsearch module in `indyscan-storage` https://github.com/Patrik-Stas/indyscan/blob/master/indyscan-storage/src/es/storage-es.js

If you implement this file, that would be great help. This would ultimately mean that this integration testsuite https://github.com/Patrik-Stas/indyscan/blob/master/indyscan-storage/test/integration/storage-es.spec.js should be passing as well (it's basically copypaste of https://github.com/Patrik-Stas/indyscan/blob/master/indyscan-storage/test/integration/storage-mongo.spec.js just different initial setup)

Next cool thing to figure out is if there should be any particular mappings set up on elasticsearch index ingesting this data, or whether any transformations should be done on this data before indexed. If nothing else, at least we should assure properly indexed timestamp field so we could have nice timeseries in Kibana and Indyscan. 

Currently there's some graphs plotted in `Stats` section in indyscan webapp, but the implementation is horrendous. I think it should become much easier and faster once the data is in ES.

**Comment by Patrik-Stas** [comment]
I've just pushed branch `elastic` with some stuff I had locally uncommitted. If you want to start working on this, might be handy start working off this branch

https://github.com/Patrik-Stas/indyscan/commit/b0e2a7166b94b1df5c16a1710397dfe9acc5f2a5

**Comment by Patrik-Stas** [comment]
@burdettadam note I've been working on this a bit over the weekend https://github.com/Patrik-Stas/indyscan/tree/elastic 
Add support to send data to ES instead of Mongo, it will be easier to contribute with some graph visualizations/views once this code stabilizes. I am now going through some trial-error process on what mappings needs to be explicitly specified for ES indices.

**Comment by Patrik-Stas** [comment]
@burdettadam  I created bunch of `GoodFirstIssue` issues for people to contribute. If you would like to help, feel free to pick one you like :-)
