### ISSUE TITLE
genesis.js?

### ISSUE THREAD

**Issue by jeffallen** [Patrik-Stas/indyscan#12]
The docs say I should be able to run "node genesis.js" to setup the genesis blocks, but I cannot find that script.

There's a "genesis" target in indyscan-daemon, so I could type "npm run genesis", but no genesis.js file.

**Comment by Patrik-Stas** [comment]
Hi Jeff, thanks for heads up! I've updated the docs and doing so I've also realized I did not push version `2.2.1` (currently deployed on indyscan.io) into the repo which contains some fixes.
