### ISSUE TITLE
libsodium not found (old -> old/unsupported)

### ISSUE THREAD

**Issue by jeffallen** [Patrik-Stas/indyscan#13]
The URL for lib sodium-1.0.14.tar.gz has changed, it now needs old/unsupported in the URL.

Here is the fix I used to solve this. You might like to use it instead of staying on 1.0.14, which the lib sodium authors would apparently prefer you did not do. :)

```
diff --git a/ubuntu-libindy/Dockerfile b/ubuntu-libindy/Dockerfile
index 7d11562..157ef97 100644
--- a/ubuntu-libindy/Dockerfile
+++ b/ubuntu-libindy/Dockerfile
@@ -39,12 +39,12 @@ RUN pip3 install -U \
 	deb-pkg-tools
 
 RUN cd /tmp && \
-   curl https://download.libsodium.org/libsodium/releases/old/libsodium-1.0.14.tar.gz | tar -xz && \
-    cd /tmp/libsodium-1.0.14 && \
+   curl https://download.libsodium.org/libsodium/releases/LATEST.tar.gz | tar -xz && \
+    cd /tmp/libsodium-* && \
     ./configure --disable-shared && \
     make && \
     make install && \
-    rm -rf /tmp/libsodium-1.0.14
+    rm -rf /tmp/libsodium-*
 
 RUN apt-get update && apt-get install openjdk-8-jdk -y
 ENV JAVA_HOME /usr/lib/jvm/java-8-openjdk-amd64
```

**Comment by Patrik-Stas** [comment]
Hi Jeff, I am not sure if the latest libsodium works well with libindy, as far as I remember there was some issues couple months earlier and newer version of NaCL didn't play with Libindy together.
Have you tried running `indyscan-daemon` container built on top of these changes?
If it works then I'll be happy to update, in such case, could you please:
1. Submit as pull request
2. Specify version of NaCL. I don't like to use latest versions is generals as it can make builds unpredictable (a newer version of NaCL comes out not compatible with IndySDK and things start to break without a modification from day to day)
